14 create js for main page
GSG-FC03/Team3-ToDoApp pull request #19
Opened 2021-07-16 17:50 UTC by Rawanzaqout

- [ ] create a function that makes the user move to the next page by click on the button

2021-07-16 17:53 UTC, adnan-afana approved these changes

2021-07-16 18:29 UTC, sara219 requested changes

2021-07-16 18:29 UTC, sara219 commented on js/main.js
> + window.location.href="..\\html\\toDolists.html"
change the path to 

```js 
    window.location.href = 'html/toDoLists.html'

```

2021-07-16 18:46 UTC, Rola-H approved these changes

2021-07-16 19:55 UTC, Rola-H approved these changes

2021-07-17 07:06 UTC, Abdelrahman059 approved these changes

2021-07-17 09:14 UTC, hshahwan approved these changes

2021-07-17 09:19 UTC, adnan-afana approved these changes

2021-07-17 14:23 UTC, merged