created file structure
GSG-FC03/Team3-ToDoApp pull request #3
Opened 2021-07-13 11:31 UTC by Abdelrahman059

Relates #2
everything is ready

2021-07-13 11:38 UTC, Rola-H approved these changes

2021-07-13 11:40 UTC, Rawanzaqout approved these changes

2021-07-13 11:42 UTC, adnan-afana approved these changes
don't miss my comment

2021-07-13 11:42 UTC, adnan-afana commented on css/style.css
> +    margin: 0%;
Add
    border-radius: 0;

2021-07-13 13:12 UTC, sara219 requested changes
- don't use uppercase to name the files, only if the file name contains two words follow the `camel case` to name the files

- change the name of the script file to `main.js`

- Create a dir called `html`, and move the `toDoList.html` into it. Only the index.html should be in the root

2021-07-14 07:49 UTC, Rawanzaqout approved these changes

2021-07-14 08:33 UTC, sara219 approved these changes

2021-07-14 08:34 UTC, merged