1 create readmefile
GSG-FC03/Team3-ToDoApp pull request #6
Opened 2021-07-14 10:12 UTC by Rawanzaqout

2021-07-14 16:34 UTC, Rola-H approved these changes

2021-07-14 18:31 UTC, adnan-afana approved these changes
Go ahead

2021-07-14 19:07 UTC, sara219 requested changes
Some Tips to make your readme better: 

- You named your project Pen so add it as a title 
- add the team members to the end of the file, and add the profile link for each one
- add the links by making the text a link `[...text](link)`
- add the technology that you use (HTML, CSS, JS ...etc)
- add **How to get and test our app** section

follow the next section for update example👇👇👇

2021-07-14 19:08 UTC, sara219 commented
# Pen

# links:

[Design Link](https://xd.adobe.com/view/91555c8d-7f64-4353-824a-03974fd2e9ba-c406/)

[live link](https://gsg-fc03.github.io/Team3-ToDoApp/)

## purpose:

Provide an application to organize time to perform tasks.

--------------------------------------------------------------------------------

## ✧ Technology we used:

- **HTML** → to build the structure of the pages
- **CSS** → to style the application
- **JS|DOM Manipulations** → To create interaction between the page and the user
- **localStorage** → to store the data

--------------------------------------------------------------------------------

## ✧ user stories

- As a user, I should be able to add my to-do to the list and save it in local storage

- As a user, I should be able to edit my to-dos

- As a user, I should be able to remove any to-do from my list (remove it from local storage)

- As a user, I can still have my list even if I close the browser window

--------------------------------------------------------------------------------

## ✧ File Structure:

```
├── index.html
├── html/
       └── toDoLists.html
├── js/
       └── main.js
├── css/
      └── style.css
      └── toDoStyle.css
      └── media.css
├── assets
├── README.md
```

--------------------------------------------------------------------------------

## ✧ How to get and test our app:

[... write the steps]

--------------------------------------------------------------------------------

## ✧ Team members :

- [Rawan Zaqout]()

- [Adnan Afana]()

- [Rola Hararah]()

- [Abdelrahman ELJazar]()

2021-07-14 21:35 UTC, Rola-H approved these changes

2021-07-14 21:52 UTC, sara219 approved these changes

2021-07-15 07:17 UTC, Abdelrahman059 approved these changes

2021-07-15 07:20 UTC, merged